server:
  port: 7878
  servlet:
    context-path: /jpa-postgres-practice
    
spring:
    application:
        name: jpa-postgres-practice
    profiles:
      active: local
logging:
  level:
      org.springframework: INFO
      com.pavikumbhar: DEBUG
---
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql : info


